------------------------------------------------------------------------------
--                 Q u a l i m e t r i c s     D r i v er                   --
--                                                                          --
--                    Copyright (C) 2012-2013, AdaCore                      --
--                                                                          --
------------------------------------------------------------------------------
with GNATCOLL.VFS;      use GNATCOLL.VFS;
with GNATCOLL.Projects; use GNATCOLL.Projects;

package Utils is

   function Return_On_Failure (Message : String) return Boolean;
   --  ???

   function Get_Deposit_Directory
     (Root_Project : Project_Type) return Virtual_File;
   --  Get Qualimetrics deposit directory.
   --  Correspond to the directory where all file generated by Qualimetrics
   --  will be dumped.
   --
   --  Returns: root project object directory if it is specified
   --           otherwise, directory of the project root file.

end Utils;
