# Create package for basic qualimetrics driver, doesn't includ GNATcheck
package:
	mkdir basic_qm_driver
	cp basic_driver/qualimetrics.py basic_qm_driver/
	# Lib
	mkdir basic_qm_driver/lib
	cp run.sh basic_qm_driver/lib/
	cp create_cp_report.py basic_qm_driver/lib/
	cp create_gcov_report.py basic_qm_driver/lib/
	cp utils.py basic_qm_driver/lib/
	cp qmt/qmt.py basic_qm_driver/lib/

clean:
	rm -rf basic_qm_driver
