CP_DOC_PATH=/Users/kiwi/code/codepeer/release/install-common/doc/users_guide/
GC_DOC_PATH=/Users/kiwi/tools/gnatpro/gnat/gnat-20121009/share/doc/gnat/txt/gnatcheck_rm.txt
all:
	python GNATtools_create_resource.py --cp_doc=$(CP_DOC_PATH) --gc_doc=$(GC_DOC_PATH)

clean:
	rm *.pyc
