#!/usr/bin/env python
import testsuite
import os
import yaml

if __name__ == '__main__':
    suite = testsuite.GNAThubTestsuite(os.path.dirname(__file__))
    suite.testsuite_main()
    # Print the results that are not OK
    all_ok = True
    for k in suite.results:
        status = suite.results[k].name
        if status not in ('PASS', 'XFAIL'):
            all_ok = False
            print("--- {} : {} ---".format(k, status))
            fname = os.path.join(suite.output_dir, "{}.yaml".format(k))
            print("See {} for more details".format(fname))
            with open(fname, 'rb') as f:
                y = f.read()
                print(yaml.safe_load(y).out)

    if all_ok:
        print("SUCCESS")
